services:
  db:
    image: mysql:latest
    container_name: maxmoll-test-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./storage/docker/db_data:/var/lib/mysql
    networks:
      - maxmoll-test-db-network

  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: maxmoll-test-app
    volumes:
      - ./:/var/www/maxmoll-test
      - ./docker/php/extend-php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./storage/docker/logs/php/:/var/logs/php/
    depends_on:
      - db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - maxmoll-test-db-network
      - maxmoll-test-webserver-network

  webserver:
    image: nginx:alpine
    container_name: maxmoll-test-webserver
    volumes:
      - ./:/var/www/maxmoll-test
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage/docker/logs/nginx/:/var/logs/nginx/
    ports:
      - "80:80"
    networks:
      - maxmoll-test-webserver-network

  redis:
    image: redis:alpine
    container_name: maxmoll-test-redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./storage/docker/redis_data:/data
    networks:
      - maxmoll-test-webserver-network

networks:
  maxmoll-test-db-network:
  maxmoll-test-webserver-network:
